---
name: 'Test updates'

on:
  push:
    branches-ignore:
      - 'master'

# on:
#   schedule:
#     - cron:  "42 7 15 * *" #build project on the 15th day of every month on the 42nd minute of the 7th hour.

env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'Set up starter-builder'
        steps: 
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install poetry
              run: |
                python -m pip install poetry==1.1.11
            - name: Configure poetry
              run: |
                python -m poetry config virtualenvs.in-project true
            - name: Cache the virtualenv
              uses: actions/cache@v2
              with:
                path: ./.venv
                key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
            - name: Install dependencies
              run: |
                python -m poetry install
            - name: Cleanup template
              run: |
                python -m poetry run doit cleanup:drupal9
            - name: 'Preparing blueprint-environment'
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.TOKEN }}
                repository: platformsh-templates/drupal9
                path: templates/drupal9/build

