---
name: 'Test updates'

on:
  push:
    branches-ignore:
      - 'master'

# on:
#   schedule:
#     - cron:  "42 7 15 * *" #build project on the 15th day of every month on the 42nd minute of the 7th hour.

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'Set up starter-builder'
        steps: 
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: '3.9' 
            - name: 'Download Poetry'
              run: |
                  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            - name: 'Install dependencies'
              run: |
                  ~/.poetry/bin/poetry install
            - name: 'Try to do something (will fail or hang)'
              run: |
                  ~/.poetry/bin/poetry run doit:full drupal9
