---
name: 'Drupal 9 updates'

on:
  push:
    branches-ignore:
      - 'master'

# on:
#   schedule:
#     - cron:  "42 7 15 * *" #build project on the 15th day of every month on the 42nd minute of the 7th hour.

env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'Set up starter-builder'
        steps: 
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install poetry
              run: |
                python -m pip install poetry==1.1.11
            - name: Configure poetry
              run: |
                python -m poetry config virtualenvs.in-project true
            - name: Cache the virtualenv
              uses: actions/cache@v2
              with:
                path: ./.venv
                key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
            - name: Install dependencies
              run: |
                python -m poetry install
            - name: 'starter-builder: cleanup'
              run: |
                python -m poetry run doit cleanup:drupal9
            - name: 'starter-builder: init'
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.TOKEN }}
                repository: platformsh-templates/drupal9
                path: templates/drupal9/build
            - name: 'starter-builder: init-remote'
              run: |
                cd templates/drupal9/build
                git remote add project https://github.com/drupal/recommended-project.git
                git config --global user.email "devrel@internal.platform.sh"
                git config --global user.name "Platform.sh DevRel bot"
            - name: 'starter-builder: update'
              run: |
                python -m poetry run doit update:drupal9
            - name: 'starter-builder: platformify'
              run: |
                python -m poetry run doit platformify:drupal9
            - name: 'starter-builder: branch'
              run: |
                python -m poetry run doit branch:drupal9
            - name: 'starter-builder: push'
              run: |
                python -m poetry run doit push:drupal9
            - name: 'starter-builder: pull-request'
              run: |
                curl -s --location --request POST --header "Authorization: Bearer $GITHUB_TOKEN" \
                    --header 'Content-Type: application/json' \
                    --data-raw '{"head": "update", "base": "master", "title": "auto-updates"}' \
                    https://api.github.com/repos/$GITHUB_REPOSITORY/pulls
